apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: helmfile
      init:
        command: ["/bin/sh", "-c"]
        args: ["helmfile repos"]
        
      generate:
        command: ["/bin/sh", "-c"]
        args: ["helmfile template"]

