apiVersion: v1
kind: Secret
metadata:
    name: vault-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:6WBDQvujR+cLhQ9OxMo3YUmPAr0QzsB5wU45nAd5UaqI03QQntewQ4iPqAyjM8eaHd6Y5MeJv2d5qnU/H+PnZZoMRFeWKFUkvWmkUEmqOb3Ln6fuMldngP/zrd1qPsS1hIujTmc7KIBdd+w=,iv:ayNIX8qgv8ZDwDBQ3iT8ejY+HgojVQp9yWs4el9fDt8=,tag:QSqf8FJQpiRSmqGDlwwPaQ==,type:str]
sops:
    age:
        - recipient: age13a0ufpltfkxxrprgj2hp2l9quamms5uea6cn2yhv9qks9d2nzawsvup3wh
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QjFiTnpXRGZHSldMaEU1
            c0Vlc1ZvbjFNbzd3RG9rSFJhYlZ1MStzSVJnCjVCUm8vWUVIQWUvY0tjbUtEUGR2
            ZFJxVVdnYko2ZGloRUxwZHV5eS9jSzQKLS0tIDd0K1hMQkhUbXFhbVNpS3Q5Vzl0
            N2M4Mnk5QXcrY0R5NzFiN2hzYXBva0EK0rNhDYM+IjqS1yTlGayUSbTCcrkg2kVR
            uRgYzf9ZiqhPlA1jY5M5tYhMLrBTiHGXNIEYu3fB3RbkiTZRYeUKCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-26T13:37:23Z"
    mac: ENC[AES256_GCM,data:H4gSDvPJEyaklFep01nr0oqiXOcCByYAdf/WClN+TPDapqfy+fx/XcVvxDDXmrB8ZQYVw47pFmqDxiOqlZTu+gXVH0kiha9nXFrLGlrvez1Rq1l0GQ7GKL//n/gVuwwQ/SoEBnIBOavcDrw3S5Jv+jRDGfyEPKy4sbzrGjiU6+I=,iv:nd8A7ai6nBCojNj0DE4yzxU3troCbOHn+e4QMTe0X/4=,tag:7tRODV/DXdcQowHhfwz6WQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
