resources:
  - namespace.yaml
  - secretprovider.yaml 
  - ../../../app-manifests/base 

namespace: dev 

patches:
  - path: patches/volume-mount.yaml
    target:
      kind: Deployment
      name: app-deployment
      
# generators 
# built-in generator
configMapGenerator:
- literals:
  - ENV=dev
  - FEATURE_FLAG=true
  name: app-config