resources:
  - namespace.yaml
  - secretprovider.yaml 
  - sa.yaml
  - ../../../app-manifests/base 

namespace: dev 

patches:
  - path: patches/volume-mount.yaml
    target:
      kind: Deployment
      name: app-deployment
  
  - path: patches/remove-env.yaml
    target:
      kind: Deployment 
      name: app-deployment
