apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-token-auth
  namespace: dev
spec:
  provider: vault
  parameters:
    vaultAddress: "https://vault-cluster-public-vault-faf4950b.3a2eac8a.z1.hashicorp.cloud:8200"
    vaultSkipVerify: "false"
    vaultNamespace: "admin"
    vaultAuthMethod: "token"
    vaultTokenSecretName: "vault-token"
    vaultTokenSecretNamespace: "default"
    vaultTokenSecretKey: "token"
    roleName: "token-auth"        # still required even if unused
    objects: |
      - objectName: db-url
        secretPath: secrets/data/db
        secretKey: url
