apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: vault-secret-provider
  namespace: dev 
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "app-k8s-role"  # Vault Kubernetes Auth role
    objects: |
      - objectName: "db-creds"
        secretPath: "kv/data/db"
        secretKey: "url"

    vaultSkipVerify: "true" # For dev or self-signed certs
    # Optional for token-based auth
    # vaultToken: "<your-root-or-app-token>" 

  secretObjects:                             # OPTIONAL: creates Kubernetes secrets
  - secretName: app-secret
    type: Opaque
    data:
    - objectName: "db-creds"
      key: url

