apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: ksops-plugin
          emptyDir: {}
      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing KSOPS...";
              mkdir -p /custom-tools/viaduct.ai/v1/ksops;
              cp /usr/local/bin/ksops /custom-tools/viaduct.ai/v1/ksops/ksops;
              chmod +x /custom-tools/viaduct.ai/v1/ksops/ksops;
              echo "Done.";
          volumeMounts:
            - name: ksops-plugin
              mountPath: /custom-tools
      containers:
        - name: repo-server
          volumeMounts:
            - name: ksops-plugin
              mountPath: /home/argocd/.config/kustomize/plugin
          env:
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /home/argocd/.config/kustomize/plugin
            - name: KUSTOMIZE_PLUGIN_LOADERS
              value: exec
