apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-store-csi-driver
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPO_URL
    targetRevision: main
    path: secret-store-csi-driver/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: ""
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
