apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: my-app-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: ClusterSecretStore
  target:
    name: my-app-k8s-secret
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD                  
      remoteRef:
        key: app/my-data/data/db           
        property: url                  
