apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: vault-secretstore
  namespace: dev
  labels:
    app.kubernetes.io/name: cluster-secret-store
spec:
  provider:
    vault:
      server: "http://vault.vault.svc:8200"   # ✅ Use port 8200 explicitly and correct DNS
      path: "kv"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "app-k8s-role"
          serviceAccountRef:
            name: "eso-sa"
