apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: app-external-secret
  namespace: dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: app-secret 
    creationPolicy: Owner
  data:
    - secretKey: DB_URL                  
      remoteRef:
        key: kv/db          
        property: url    

    #- secretKey: DB_PASSWORD
    #  remoteRef:
    #    key: app/my-data/data/db 
    #    property: password 

    #- secretKey: DB_USER
    #  remoteRef:
    #    key: app/my-data/data/db 
    #    property: user 
    
    #- secretKey: DB_PORT
    #  remoteRef:
    #    key: app/my-data/data/db 
    #    property: port 

