resources:
  - ../../../app-manifests/base
  - namespace.yaml
  - secret-store.yaml
  - external-secret.yaml

namespace: dev 

# generators 
# built-in generator
configMapGenerator:
- literals:
  - ENV=dev
  - FEATURE_FLAG=true
  name: app-config
