apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: vault-store
spec:
  provider:
    vault:
      server: "https://vault-cluster-public-vault-15f198f6.b3123219.z1.hashicorp.cloud:8200"
      path: "app/my-data" 
      version: "v2"
      namespace: "admin/"               # Required if you're in the `admin/` namespace
      auth:
        tokenSecretRef:
          name: vault-token             # SOPS-encrypted Kubernetes Secret with Vault token
          key: token
          namespace: default
